### ISSUE TITLE
3D visualization: ValueError: 'arr' does not have a suitable array shape for any mode.

### ISSUE THREAD

**Issue by sodaGH** [raghakot/keras-vis#112]
Thanks for your great work!
I want to visualize the grad-CAM figure for my 3D data image. However, I met some problem at this line:
`        grads = visualize_cam(model, layer_idx, filter_indices=20, 
                              seed_input=img, backprop_modifier=modifier) `
in the code block:
`import numpy as np
import matplotlib.cm as cm
from vis.visualization import visualize_cam

for modifier in [None, 'guided', 'relu']:
    plt.figure()
    f, ax = plt.subplots(1, 2)
    plt.suptitle("vanilla" if modifier is None else modifier)
    for i, img in enumerate([img1, img2]):    
        # 20 is the imagenet index corresponding to `ouzel`
        grads = visualize_cam(model, layer_idx, filter_indices=20, 
                              seed_input=img, backprop_modifier=modifier)        
        # Lets overlay the heatmap onto original image.    
        jet_heatmap = np.uint8(cm.jet(grads)[..., :3] * 255)
        ax[i].imshow(overlay(jet_heatmap, img))`

It returns the error:
`Traceback (most recent call last):
  File "CNN_vis_CAM.py", line 319, in <module>
    seed_input=img, backprop_modifier=modifier)        
  File "/usr/local/lib/python2.7/dist-packages/vis/visualization/saliency.py", line 239, in visualize_cam
    return visualize_cam_with_losses(model.input, losses, seed_input, penultimate_layer, grad_modifier)
  File "/usr/local/lib/python2.7/dist-packages/vis/visualization/saliency.py", line 186, in visualize_cam_with_losses
    heatmap = imresize(heatmap, input_dims, interp='bicubic', mode='F')
  File "/usr/local/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 480, in imresize
    im = toimage(arr, mode=mode)
  File "/usr/local/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 289, in toimage
    raise ValueError("'arr' does not have a suitable array shape for "
ValueError: 'arr' does not have a suitable array shape for any mode.
`

My data size is 49*41*40, and I succeed in drawing the saliency figure. Do you know how to fix this problem? Thanks for your reading! And looking forward to your reply.

**Comment by CanPhi** [comment]
I would also be interested in whether this can be used for 3D inputs.

**Comment by keisen** [comment]
I think the direct cause of the error has already been corrected in current master branch.
But, the problem I wrote in issues#113 also occurs here.
If you are using Conv2D, please execute the step in issue#113.

* keras-vis 0.4.1
https://github.com/raghakot/keras-vis/blob/e6ef1d7c0dee7fc90e57c82ff720dc3eafc9c365/vis/visualization/saliency.py#L185-L186

* current master branch
https://github.com/raghakot/keras-vis/blob/e019cc43ce6c00b2151941b18dbad63164ad632a/vis/visualization/saliency.py#L184-L188

**Comment by jalilahmed** [comment]
I am having the same issue. I have a 3D VGG.  Saliency Maps are generated by visualize_cam doesnt work.

**Comment by keisen** [comment]
@jalilahmed , Can I see the error log of  your issue ?

**Comment by jalilahmed** [comment]
@keisen The library was NOT UPDATED. Doing an UPDATE removed the error. Thanks for your quick response.

**Comment by WAMAWAMA** [comment]
> @keisen The library was NOT UPDATED. Doing an UPDATE removed the error. Thanks for your quick response.
I also have the problem(Saliency Maps are generated by visualize_cam doesn't work.), can u tell me which library u updated? my current version is :keras-vis 0.4.1  keras2.1.0  TF 1.4.0.Looking forward to your reply.

**Comment by WAMAWAMA** [comment]
@jalilahmed  The library was NOT UPDATED. Doing an UPDATE removed the error. Thanks for your quick response.
I also have the problem(Saliency Maps are generated by visualize_cam doesn't work.), can u tell me which library u updated? my current version is :keras-vis 0.4.1 keras2.1.0 TF 1.4.0.Looking forward to your reply.

**Comment by WAMAWAMA** [comment]
@jalilahmed I also have the problem(Saliency Maps are generated by visualize_cam doesn't work.), can u tell me which library u updated? my current version is :keras-vis 0.4.1 keras2.1.0 TF 1.4.0.Looking forward to your reply.

**Comment by WAMAWAMA** [comment]
I also have the problem(Saliency Maps are generated by visualize_cam doesn't work.), can u tell me which library u updated? my current version is : keras-vis 0.4.1   keras2.1.0    TF 1.4.0.  Looking forward to your reply.

**Comment by WAMAWAMA** [comment]
@jalilahmed I also have the problem(Saliency Maps are generated by visualize_cam doesn't work.), can u tell me which library u updated? my current version is : keras-vis 0.4.1 keras2.1.0 TF 1.4.0. Looking forward to your reply.

**Comment by mh2t** [comment]
@keisen , I'm trying to visualize on InceptionV3. I got same error:

`InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in _create_c_op(graph, node_def, inputs, control_inputs)
   1863   try:
-> 1864     c_op = c_api.TF_FinishOperation(op_desc)
   1865   except errors.InvalidArgumentError as e:

InvalidArgumentError: slice index 20 of dimension 1 out of bounds. for 'strided_slice_5' (op: 'StridedSlice') with input shapes: [?,2], [2], [2], [2] and with computed input tensors: input[1] = <0 20>, input[2] = <0 21>, input[3] = <1 1>.

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
12 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in _create_c_op(graph, node_def, inputs, control_inputs)
   1865   except errors.InvalidArgumentError as e:
   1866     # Convert to ValueError for backwards compatibility.
-> 1867     raise ValueError(str(e))
   1868 
   1869   return c_op

ValueError: slice index 20 of dimension 1 out of bounds. for 'strided_slice_5' (op: 'StridedSlice') with input shapes: [?,2], [2], [2], [2] and with computed input tensors: input[1] = <0 20>, input[2] = <0 21>, input[3] = <1 1>.
`
