### ISSUE TITLE
tensorflow.python.framework.errors.InvalidArgumentError: input_1:0 is both fed and fetched.

### ISSUE THREAD

**Issue by simonlight** [raghakot/keras-vis#14]
Working on filters: [292]
Traceback (most recent call last):
  File "/home/wangxin/code/generative_seed/guiding_saliency.py", line 35, in <module>
    heatmap = visualize_saliency(model, layer_idx, [pred_class], seed_img, text=utils.get_imagenet_label(pred_class))
  File "/home/wangxin/.local/lib/python2.7/site-packages/vis/visualization.py", line 146, in visualize_saliency
    grads = opt.minimize(max_iter=1, verbose=False, jitter=0, seed_img=seed_img)[1]
  File "/home/wangxin/.local/lib/python2.7/site-packages/vis/optimizer.py", line 152, in minimize
    loss, grads, wrt_value = self.overall_loss_grad_wrt_fn([seed_img, 0])
  File "/home/wangxin/.local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1943, in __call__
    feed_dict=feed_dict)
  File "/home/wangxin/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 372, in run
    run_metadata_ptr)
  File "/home/wangxin/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 636, in _run
    feed_dict_string, options, run_metadata)
  File "/home/wangxin/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 708, in _do_run
    target_list, options, run_metadata)
  File "/home/wangxin/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 728, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: input_1:0 is both fed and fetched.

I saw this while i'm running the example on https://raghakot.github.io/keras-vis/visualizations/attention/. Could someone help me figure it out?

**Comment by raghakot** [comment]
I just pushed a bunch of fixes. Can you try this again?
It would also be helpful to post the full code that fails. Perhaps the docs are simply out of date...

**Comment by simonlight** [comment]
It works now. Thx @raghakot 
I could not find out the code I used for producing the error... 
I'll remember to do this in the future.

**Comment by raghakot** [comment]
cool.
