### ISSUE TITLE
 can I using keras_vis for YOLO3

### ISSUE THREAD

**Issue by zzusunjs** [raghakot/keras-vis#171]
The error I encountered is quite weird, I am trying to use keras_vis to visualize the feature maps in  a YOLO_v3 model implemented by Keras. But the `utils.apply_modifications` can't work 
```
 Traceback (most recent call last):
  File "yolo_max_activation.py", line 29, in <module>
    model = utils.apply_modifications(model)
  File "/home/gt/anaconda3/lib/python3.6/site-packages/vis/utils/utils.py", line 124, in apply_modifications
    return load_model(model_path)
  File "/home/gt/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/home/gt/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/gt/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/gt/anaconda3/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/gt/anaconda3/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/gt/anaconda3/lib/python3.6/site-packages/keras/engine/network.py", line 1032, in from_config
    process_node(layer, node_data)
  File "/home/gt/anaconda3/lib/python3.6/site-packages/keras/engine/network.py", line 991, in process_node
    layer(unpack_singleton(input_tensors), **kwargs)
  File "/home/gt/anaconda3/lib/python3.6/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/gt/anaconda3/lib/python3.6/site-packages/keras/layers/core.py", line 687, in call
    return self.function(inputs, **arguments)
  File "/media/gt/4d8cfabd-1da1-4e39-8edc-eaceea722b34/zq_workspace/keras-yolo3-master/yolo3/model.py", line 376, in yolo_loss
    grid, raw_pred, pred_xy, pred_wh = yolo_head(yolo_outputs[l],
NameError: name 'yolo_head' is not defined
```

The yolo_head function is defined in the same file.  And then I realized  that the modify operation might not necessary and I comment out the modify parts.After that another errors occured:

```
Traceback (most recent call last):
  File "yolo_max_activation.py", line 31, in <module>
    0., 1.), tv_weight=10, lp_norm_weight=0.)
  File "/home/gt/anaconda3/lib/python3.6/site-packages/vis/visualization/activation_maximization.py", line 107, in visualize_activation
    return visualize_activation_with_losses(model.input, losses, seed_input, input_range, **optimizer_params)
  File "/home/gt/anaconda3/lib/python3.6/site-packages/vis/visualization/activation_maximization.py", line 40, in visualize_activation_with_losses
    opt = Optimizer(input_tensor, losses, input_range)
  File "/home/gt/anaconda3/lib/python3.6/site-packages/vis/optimizer.py", line 46, in __init__
    loss_fn = weight * loss.build_loss()
  File "/home/gt/anaconda3/lib/python3.6/site-packages/vis/regularizers.py", line 52, in build_loss
    image_dims = K.ndim(self.img) - 2
  File "/home/gt/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 619, in ndim
    dims = x.get_shape()._dims
AttributeError: 'list' object has no attribute 'get_shape'
```

I wonder if it is because the keras-vis can't support models with  leaky ReLU  ??

**Comment by abhigoku10** [comment]
@zzusunjs  hi i am also pursing the same problem , were you able to visualize the yolov3. If so can you please share the procedure
